services:
  # =========================
  # Laravel
  # PHP-FPM + Nginx
  # =========================
  app:
    build:
      context: ./apps/back
      dockerfile: docker/production/Dockerfile
    container_name: ecommerce-app
    restart: unless-stopped
    env_file:
      - ./apps/back/.env
    volumes:
      - laravel_storage:/var/www/storage/app/public
    networks:
      - ecommerce

  # =========================
  # MySQL
  # =========================
  mysql:
    image: mysql:8.4
    container_name: ecommerce-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: ecommerce
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce

  # =========================
  # Next.js
  # =========================
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: https://galalstore.duckdns.org
        NEXT_PUBLIC_URL: https://galalstore.duckdns.org
    container_name: ecommerce-client
    restart: unless-stopped
    environment:
      NODE_ENV: production
      API_INTERNAL_URL: http://app
    depends_on:
      - app
    networks:
      - ecommerce

    # =========================
  # Next.js Admin
  # =========================
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: https://galalstore.duckdns.org
        NEXT_PUBLIC_BASE_API_URL: https://galalstore.duckdns.org
    container_name: ecommerce-admin
    restart: unless-stopped
    environment:
      NODE_ENV: production
      API_INTERNAL_URL: http://app
    depends_on:
      - app
    networks:
      - ecommerce

    # =========================
  # Vite CMS
  # =========================
  cms:
    build:
      context: .
      dockerfile: apps/cms/Dockerfile.prod
      args:
        VITE_API_URL: https://galalstore.duckdns.org
    container_name: ecommerce-cms
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - ecommerce

  # =========================
  # Public Nginx
  # =========================
  nginx:
    image: nginx:1.27-alpine
    container_name: ecommerce-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - laravel_storage:/var/www/storage/app/public:ro
      - ./docker/certbot/www:/var/www/certbot:ro
      - ./docker/certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - app
      - client
    networks:
      - ecommerce

    # =========================
  # Qdrant
  # =========================
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ecommerce-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - ecommerce

  n8n:
    image: n8nio/n8n:latest
    container_name: ecommerce-n8n
    restart: unless-stopped
    environment:
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      N8N_HOST: n8n-galalstore.duckdns.org
      WEBHOOK_URL: https://nngalalstore.duckdns.org/
      GENERIC_TIMEZONE: Africa/Cairo
      TZ: Africa/Cairo
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - ecommerce

  certbot:
    image: certbot/certbot:latest
    container_name: ecommerce-certbot
    volumes:
      - ./docker/certbot/www:/var/www/certbot
      - ./docker/certbot/conf:/etc/letsencrypt
    networks:
      - ecommerce

networks:
  ecommerce:

volumes:
  mysql_data:
  laravel_storage:
  n8n_data:
