server {
    listen 80;
    server_name _;

    root /var/www/public;

    index index.php index.html;

    client_max_body_size 50M;

    location /storage/ {
        alias /var/www/storage/app/public/;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
# Next.js Admin
location /admin/ {
    proxy_pass http://admin:3000/;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
    }

    location ~ /\.ht {
        deny all;
    }
}