FROM node:22-alpine AS builder

WORKDIR /workspace

COPY package.json package-lock.json ./

COPY apps/cms/package.json ./apps/cms/package.json
COPY packages/sharedSections/package.json ./packages/sharedSections/package.json

RUN npm ci

COPY apps/cms ./apps/cms
COPY packages/sharedSections ./packages/sharedSections

WORKDIR /workspace/apps/cms

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build


FROM nginx:1.27-alpine

COPY --from=builder /workspace/apps/cms/dist /usr/share/nginx/html

COPY apps/cms/docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]